### ISSUE TITLE
Any HTTP Client sending error is logged as status 400 response

### ISSUE THREAD

**Issue by jolisper** [fortio/fortio#510] opened 2022-02-14 20:26 UTC
https://github.com/fortio/fortio/blob/4a325b93146c7faf5d7ff5a327d3c86abceb141f/fhttp/http_client.go#L377

Why is any HTTP client sending error added in the statistics as a status 400 response? 

For instance if I run a test over an http endpoint expecting an httpS endpoint, the client fail negotiating the encryption but all the requests are logged as a status 400 response from the server, hiding the real problem, and also dirtying the statistics.

**Comment by ldemailly** [comment] 2022-02-20 23:38
well first, fortio won't start a load test if you get these errors; unless you force it to ignore warm up errors

second this is only in the "standard client" mode

this being said maybe I can make it closer to the fast client and use -1 for these errors (but conceptually these _are_ 400s : bad client requests)

**Comment by Anhellikal** [comment] 2022-02-22 21:30
Hi, we actually found this issue when load testing  and endpoint that was behind a gateway with TLS, since this error occurs in fortio only and its sporadically it wont stop the test.
However in the results it would be marked as status code 400. We spend quite some time figuring it out if it was the gateway/backend since a status code implies a response from the endpoint, until we found that in fortio any error is defaulted to 400 in http_client.go. I dont think a load generation tool should return/log a http status code when the issue is not returned by the endpoint you are testing.
if you can change it to -1 I think it would be more clear that the issue is with the load generation tool and not with the endpoint being tested.

**Comment by jolisper** [comment] 2022-02-23 16:46
I think that @Anhellikal express the key point: is misleading that the Fortio http client force an 400 status response metric when the tested endpoint is not responding that. In the case of "connection refuse" the status code is showed as -1, I think that this option is better and applicable to this case too.

**Comment by ldemailly** [comment] 2022-02-25 21:32
Thanks, do you have an example of the output of line above (376), I'd like to see what the error was so I can reproduce it 

https://github.com/fortio/fortio/blob/4a325b93146c7faf5d7ff5a327d3c86abceb141f/fhttp/http_client.go#L376-L377

and/or how you get these errors intermittently ? how to reproduce?
(feel free to remove actual url/ip from the sample for privacy)

**Closed as completed** 2022-02-27 18:59 UTC
