### ISSUE TITLE
Support for -cacert for http calls

### ISSUE THREAD

**Issue by bseenu** [fortio/fortio#470] opened 2021-05-21 22:00 UTC
```
-cacert Path
    	Path to a custom CA certificate file to be used for the GRPC client TLS, if empty, use https:// prefix for standard internet CAs TLS
```

Is ca-cert only for grpc clients? , can we add the support for http as well

```
bash-3.2$ fortio curl -cacert /tmp/ca.crt https://example.com/test
14:54:39 W http_client.go:146> https requested, switching to standard go client
14:54:39 E http_client.go:371> Unable to send GET request for https://example.com/test: Get "https://example.com/test": x509: certificate signed by unknown authority
Get "https://example.com/test": x509: certificate signed by unknown authority14:54:39 E commonflags.go:131> Error status 400 : Get \"https://example.com/test\": x509: certificate signed by unknown authority
```
```
bash-3.2$ fortio version
1.14.2 2021-03-10 22:41 ee098c572115f4149a67d2a812cb3d1ca79e30e1 go1.16
```

PS: the dns name has been changed

**Comment by ldemailly** [comment] 2021-05-22 15:12
yes we should, duplicate of #329

**Closed as completed** 2021-05-22 15:12 UTC
