### ISSUE TITLE
Web/Graphical UI can't generate the chart

### ISSUE THREAD

**Issue by zxDiscovery** [fortio/fortio#265] opened 2018-06-26 09:01 UTC
Istio-0.8 at max QPS, 48 connections for 30s between 2 services inside the mesh(S1 to S2)

Result graphing generate failed and the log as follows:

```
[2018-06-20 06:54:59.477][55][info][client] external/envoy/source/common/http/codec_client.cc:117] [C166] protocol error: http/1.1 protocol error: HPE_INVALID_EOF_STATE
```

/cc @gyliu513 @morvencao

**Comment by morvencao** [comment] 2018-06-26 09:10
@ThanosAndLichKing Can you provide the reproduce steps and complete logs?

**Comment by ldemailly** [comment] 2018-06-26 15:29
specially the full output on fortio side

**Comment by ldemailly** [comment] 2018-06-28 17:47
This seems to be an istio issue so I'm going to close this, please file a new issue in istio/istio with all the details - including the full fortio output

**Closed as completed by ldemailly** 2018-06-28 17:47 UTC
